<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: begdocs-master/codigo_ejemplo/qr/qr.proto

namespace Qr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>qr.HeaderAndBody</code>
 */
class HeaderAndBody extends \Google\Protobuf\Internal\Message
{
    /**
     * Datos publicos del mensaje
     *
     * Generated from protobuf field <code>.qr.Header header = 1;</code>
     */
    protected $header = null;
    /**
     * Cuerpo del mensaje
     *
     * Generated from protobuf field <code>bytes body = 2;</code>
     */
    protected $body = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Qr\Header $header
     *           Datos publicos del mensaje
     *     @type string $body
     *           Cuerpo del mensaje
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BegdocsMaster\CodigoEjemplo\Qr\Qr::initOnce();
        parent::__construct($data);
    }

    /**
     * Datos publicos del mensaje
     *
     * Generated from protobuf field <code>.qr.Header header = 1;</code>
     * @return \Qr\Header|null
     */
    public function getHeader()
    {
        return isset($this->header) ? $this->header : null;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Datos publicos del mensaje
     *
     * Generated from protobuf field <code>.qr.Header header = 1;</code>
     * @param \Qr\Header $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Qr\Header::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Cuerpo del mensaje
     *
     * Generated from protobuf field <code>bytes body = 2;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Cuerpo del mensaje
     *
     * Generated from protobuf field <code>bytes body = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

}

