<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: begdocs-master/codigo_ejemplo/qr/qr.proto

namespace Qr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>qr.Header</code>
 */
class Header extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.qr.SigScheme signature_scheme = 1;</code>
     */
    protected $signature_scheme = 0;
    /**
     * Generated from protobuf field <code>.qr.EncScheme encryption_scheme = 2;</code>
     */
    protected $encryption_scheme = 0;
    /**
     * Generated from protobuf field <code>.qr.MessageKind message_kind = 3;</code>
     */
    protected $message_kind = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $signature_scheme
     *     @type int $encryption_scheme
     *     @type int $message_kind
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BegdocsMaster\CodigoEjemplo\Qr\Qr::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.qr.SigScheme signature_scheme = 1;</code>
     * @return int
     */
    public function getSignatureScheme()
    {
        return $this->signature_scheme;
    }

    /**
     * Generated from protobuf field <code>.qr.SigScheme signature_scheme = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSignatureScheme($var)
    {
        GPBUtil::checkEnum($var, \Qr\SigScheme::class);
        $this->signature_scheme = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.qr.EncScheme encryption_scheme = 2;</code>
     * @return int
     */
    public function getEncryptionScheme()
    {
        return $this->encryption_scheme;
    }

    /**
     * Generated from protobuf field <code>.qr.EncScheme encryption_scheme = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEncryptionScheme($var)
    {
        GPBUtil::checkEnum($var, \Qr\EncScheme::class);
        $this->encryption_scheme = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.qr.MessageKind message_kind = 3;</code>
     * @return int
     */
    public function getMessageKind()
    {
        return $this->message_kind;
    }

    /**
     * Generated from protobuf field <code>.qr.MessageKind message_kind = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageKind($var)
    {
        GPBUtil::checkEnum($var, \Qr\MessageKind::class);
        $this->message_kind = $var;

        return $this;
    }

}

