<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: begdocs-master/codigo_ejemplo/qr/qr.proto

namespace Qr;

use UnexpectedValueException;

/**
 * Tipo de mensajes a ser disponibles a ser codificados en el cuerpo
 *
 * Protobuf type <code>qr.MessageKind</code>
 */
class MessageKind
{
    /**
     * Generated from protobuf enum <code>QRActivatePuestoKind = 0;</code>
     */
    const QRActivatePuestoKind = 0;
    /**
     * Generated from protobuf enum <code>QRVoucherKind = 1;</code>
     */
    const QRVoucherKind = 1;

    private static $valueToName = [
        self::QRActivatePuestoKind => 'QRActivatePuestoKind',
        self::QRVoucherKind => 'QRVoucherKind',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

