<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: begdocs-master/codigo_ejemplo/qr/qr.proto

namespace Qr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QR codificado para activar un puesto
 *
 * Generated from protobuf message <code>qr.QRActivatePuesto</code>
 */
class QRActivatePuesto extends \Google\Protobuf\Internal\Message
{
    /**
     * nombre de la empresa 
     *
     * Generated from protobuf field <code>string empresa_nombre = 1;</code>
     */
    protected $empresa_nombre = '';
    /**
     * identificador de empresa
     *
     * Generated from protobuf field <code>uint32 empresa_id = 2;</code>
     */
    protected $empresa_id = 0;
    /**
     * identificador de puesto
     *
     * Generated from protobuf field <code>uint32 puesto_id = 3;</code>
     */
    protected $puesto_id = 0;
    /**
     * array de identificadores recorridos validos cargados en el sistema
     *
     * Generated from protobuf field <code>repeated uint32 recorridos = 4;</code>
     */
    private $recorridos;
    /**
     * url utilizada para rendir los vouchers
     *
     * Generated from protobuf field <code>string url_api = 5;</code>
     */
    protected $url_api = '';
    /**
     * token de autorización que debe ser utilizado en url_api para autenticacion
     *
     * Generated from protobuf field <code>string token = 6;</code>
     */
    protected $token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $empresa_nombre
     *           nombre de la empresa 
     *     @type int $empresa_id
     *           identificador de empresa
     *     @type int $puesto_id
     *           identificador de puesto
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $recorridos
     *           array de identificadores recorridos validos cargados en el sistema
     *     @type string $url_api
     *           url utilizada para rendir los vouchers
     *     @type string $token
     *           token de autorización que debe ser utilizado en url_api para autenticacion
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BegdocsMaster\CodigoEjemplo\Qr\Qr::initOnce();
        parent::__construct($data);
    }

    /**
     * nombre de la empresa 
     *
     * Generated from protobuf field <code>string empresa_nombre = 1;</code>
     * @return string
     */
    public function getEmpresaNombre()
    {
        return $this->empresa_nombre;
    }

    /**
     * nombre de la empresa 
     *
     * Generated from protobuf field <code>string empresa_nombre = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEmpresaNombre($var)
    {
        GPBUtil::checkString($var, True);
        $this->empresa_nombre = $var;

        return $this;
    }

    /**
     * identificador de empresa
     *
     * Generated from protobuf field <code>uint32 empresa_id = 2;</code>
     * @return int
     */
    public function getEmpresaId()
    {
        return $this->empresa_id;
    }

    /**
     * identificador de empresa
     *
     * Generated from protobuf field <code>uint32 empresa_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEmpresaId($var)
    {
        GPBUtil::checkUint32($var);
        $this->empresa_id = $var;

        return $this;
    }

    /**
     * identificador de puesto
     *
     * Generated from protobuf field <code>uint32 puesto_id = 3;</code>
     * @return int
     */
    public function getPuestoId()
    {
        return $this->puesto_id;
    }

    /**
     * identificador de puesto
     *
     * Generated from protobuf field <code>uint32 puesto_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPuestoId($var)
    {
        GPBUtil::checkUint32($var);
        $this->puesto_id = $var;

        return $this;
    }

    /**
     * array de identificadores recorridos validos cargados en el sistema
     *
     * Generated from protobuf field <code>repeated uint32 recorridos = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRecorridos()
    {
        return $this->recorridos;
    }

    /**
     * array de identificadores recorridos validos cargados en el sistema
     *
     * Generated from protobuf field <code>repeated uint32 recorridos = 4;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRecorridos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->recorridos = $arr;

        return $this;
    }

    /**
     * url utilizada para rendir los vouchers
     *
     * Generated from protobuf field <code>string url_api = 5;</code>
     * @return string
     */
    public function getUrlApi()
    {
        return $this->url_api;
    }

    /**
     * url utilizada para rendir los vouchers
     *
     * Generated from protobuf field <code>string url_api = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUrlApi($var)
    {
        GPBUtil::checkString($var, True);
        $this->url_api = $var;

        return $this;
    }

    /**
     * token de autorización que debe ser utilizado en url_api para autenticacion
     *
     * Generated from protobuf field <code>string token = 6;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * token de autorización que debe ser utilizado en url_api para autenticacion
     *
     * Generated from protobuf field <code>string token = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

}

