<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: begdocs-master/codigo_ejemplo/qr/qr.proto

namespace Qr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>qr.QRVoucher</code>
 */
class QRVoucher extends \Google\Protobuf\Internal\Message
{
    /**
     * identificador de voucher
     *
     * Generated from protobuf field <code>uint32 voucher_id = 1;</code>
     */
    protected $voucher_id = 0;
    /**
     * tipo de voucher
     *
     * Generated from protobuf field <code>uint32 tipo_voucher = 2;</code>
     */
    protected $tipo_voucher = 0;
    /**
     * tipo de beneficiario
     *
     * Generated from protobuf field <code>uint32 tipo_beneficio = 3;</code>
     */
    protected $tipo_beneficio = 0;
    /**
     * fecha de viaje
     *
     * Generated from protobuf field <code>.qr.Date fecha = 4;</code>
     */
    protected $fecha = null;
    /**
     * identificador de empresa
     *
     * Generated from protobuf field <code>uint32 empresa_id = 5;</code>
     */
    protected $empresa_id = 0;
    /**
     * identificador de recorrido 
     *
     * Generated from protobuf field <code>uint32 recorrido = 6;</code>
     */
    protected $recorrido = 0;
    /**
     * número de documento de beneficiario
     *
     * Generated from protobuf field <code>uint32 documento = 7;</code>
     */
    protected $documento = 0;
    /**
     * apellido y nombre beneficiario
     *
     * Generated from protobuf field <code>string nombre = 8;</code>
     */
    protected $nombre = '';
    /**
     * localidad de origen y destino
     *
     * Generated from protobuf field <code>string desde_hasta = 9;</code>
     */
    protected $desde_hasta = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $voucher_id
     *           identificador de voucher
     *     @type int $tipo_voucher
     *           tipo de voucher
     *     @type int $tipo_beneficio
     *           tipo de beneficiario
     *     @type \Qr\Date $fecha
     *           fecha de viaje
     *     @type int $empresa_id
     *           identificador de empresa
     *     @type int $recorrido
     *           identificador de recorrido 
     *     @type int $documento
     *           número de documento de beneficiario
     *     @type string $nombre
     *           apellido y nombre beneficiario
     *     @type string $desde_hasta
     *           localidad de origen y destino
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BegdocsMaster\CodigoEjemplo\Qr\Qr::initOnce();
        parent::__construct($data);
    }

    /**
     * identificador de voucher
     *
     * Generated from protobuf field <code>uint32 voucher_id = 1;</code>
     * @return int
     */
    public function getVoucherId()
    {
        return $this->voucher_id;
    }

    /**
     * identificador de voucher
     *
     * Generated from protobuf field <code>uint32 voucher_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVoucherId($var)
    {
        GPBUtil::checkUint32($var);
        $this->voucher_id = $var;

        return $this;
    }

    /**
     * tipo de voucher
     *
     * Generated from protobuf field <code>uint32 tipo_voucher = 2;</code>
     * @return int
     */
    public function getTipoVoucher()
    {
        return $this->tipo_voucher;
    }

    /**
     * tipo de voucher
     *
     * Generated from protobuf field <code>uint32 tipo_voucher = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTipoVoucher($var)
    {
        GPBUtil::checkUint32($var);
        $this->tipo_voucher = $var;

        return $this;
    }

    /**
     * tipo de beneficiario
     *
     * Generated from protobuf field <code>uint32 tipo_beneficio = 3;</code>
     * @return int
     */
    public function getTipoBeneficio()
    {
        return $this->tipo_beneficio;
    }

    /**
     * tipo de beneficiario
     *
     * Generated from protobuf field <code>uint32 tipo_beneficio = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTipoBeneficio($var)
    {
        GPBUtil::checkUint32($var);
        $this->tipo_beneficio = $var;

        return $this;
    }

    /**
     * fecha de viaje
     *
     * Generated from protobuf field <code>.qr.Date fecha = 4;</code>
     * @return \Qr\Date|null
     */
    public function getFecha()
    {
        return isset($this->fecha) ? $this->fecha : null;
    }

    public function hasFecha()
    {
        return isset($this->fecha);
    }

    public function clearFecha()
    {
        unset($this->fecha);
    }

    /**
     * fecha de viaje
     *
     * Generated from protobuf field <code>.qr.Date fecha = 4;</code>
     * @param \Qr\Date $var
     * @return $this
     */
    public function setFecha($var)
    {
        GPBUtil::checkMessage($var, \Qr\Date::class);
        $this->fecha = $var;

        return $this;
    }

    /**
     * identificador de empresa
     *
     * Generated from protobuf field <code>uint32 empresa_id = 5;</code>
     * @return int
     */
    public function getEmpresaId()
    {
        return $this->empresa_id;
    }

    /**
     * identificador de empresa
     *
     * Generated from protobuf field <code>uint32 empresa_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setEmpresaId($var)
    {
        GPBUtil::checkUint32($var);
        $this->empresa_id = $var;

        return $this;
    }

    /**
     * identificador de recorrido 
     *
     * Generated from protobuf field <code>uint32 recorrido = 6;</code>
     * @return int
     */
    public function getRecorrido()
    {
        return $this->recorrido;
    }

    /**
     * identificador de recorrido 
     *
     * Generated from protobuf field <code>uint32 recorrido = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setRecorrido($var)
    {
        GPBUtil::checkUint32($var);
        $this->recorrido = $var;

        return $this;
    }

    /**
     * número de documento de beneficiario
     *
     * Generated from protobuf field <code>uint32 documento = 7;</code>
     * @return int
     */
    public function getDocumento()
    {
        return $this->documento;
    }

    /**
     * número de documento de beneficiario
     *
     * Generated from protobuf field <code>uint32 documento = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setDocumento($var)
    {
        GPBUtil::checkUint32($var);
        $this->documento = $var;

        return $this;
    }

    /**
     * apellido y nombre beneficiario
     *
     * Generated from protobuf field <code>string nombre = 8;</code>
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * apellido y nombre beneficiario
     *
     * Generated from protobuf field <code>string nombre = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setNombre($var)
    {
        GPBUtil::checkString($var, True);
        $this->nombre = $var;

        return $this;
    }

    /**
     * localidad de origen y destino
     *
     * Generated from protobuf field <code>string desde_hasta = 9;</code>
     * @return string
     */
    public function getDesdeHasta()
    {
        return $this->desde_hasta;
    }

    /**
     * localidad de origen y destino
     *
     * Generated from protobuf field <code>string desde_hasta = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDesdeHasta($var)
    {
        GPBUtil::checkString($var, True);
        $this->desde_hasta = $var;

        return $this;
    }

}

