<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: begdocs-master/codigo_ejemplo/qr/qr.proto

namespace Qr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Cada mensaje seguro es de este tipo y tiene un encabezado y cuerpo y firma digital
 *
 * Generated from protobuf message <code>qr.SecureMessage</code>
 */
class SecureMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * header_and_body es un array de bytes y debe contener un mensaje de tipo HeaderAndBody 
     *
     * Generated from protobuf field <code>bytes header_and_body = 1;</code>
     */
    protected $header_and_body = '';
    /**
     * firma de header_and_body
     *
     * Generated from protobuf field <code>bytes signature = 2;</code>
     */
    protected $signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $header_and_body
     *           header_and_body es un array de bytes y debe contener un mensaje de tipo HeaderAndBody 
     *     @type string $signature
     *           firma de header_and_body
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BegdocsMaster\CodigoEjemplo\Qr\Qr::initOnce();
        parent::__construct($data);
    }

    /**
     * header_and_body es un array de bytes y debe contener un mensaje de tipo HeaderAndBody 
     *
     * Generated from protobuf field <code>bytes header_and_body = 1;</code>
     * @return string
     */
    public function getHeaderAndBody()
    {
        return $this->header_and_body;
    }

    /**
     * header_and_body es un array de bytes y debe contener un mensaje de tipo HeaderAndBody 
     *
     * Generated from protobuf field <code>bytes header_and_body = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHeaderAndBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->header_and_body = $var;

        return $this;
    }

    /**
     * firma de header_and_body
     *
     * Generated from protobuf field <code>bytes signature = 2;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * firma de header_and_body
     *
     * Generated from protobuf field <code>bytes signature = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

}

